<a href="https://colab.research.google.com/github/quanap5kr/DeepTest/blob/master/RecurentNeuralNetworkLSTMTest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/gdrive/')

Drive already mounted at /content/gdrive/; to attempt to forcibly remount, call drive.mount("/content/gdrive/", force_remount=True).


###LSTM-RNN Test 01

In [5]:
from keras.models import Model
from keras.layers import Input
from keras.layers import LSTM
from numpy import array
import keras
import warnings
warnings.filterwarnings('ignore')

k_init = keras.initializers.Constant(value=0.1)
b_init = keras.initializers.Constant(value=0.05)
r_init = keras.initializers.Constant(value=0.1)
# LSTM units
units = 2

# define model
inputs1 = Input(shape=(3, 2))
# we should setting recurrent_activation = 'sigmoid' because default as 'hard_sigmoid'
lstm = LSTM(units, return_sequences = True, recurrent_activation='sigmoid', use_bias=False, activation='tanh',kernel_initializer=k_init, bias_initializer=b_init, recurrent_initializer=r_init)(inputs1)
model = Model(inputs=inputs1, outputs=lstm)
# define input data
data = array([0.1, 0.2, 0.3, 0.1, 0.2, 0.3]).reshape((1,3,2))
# make and show prediction
output = model.predict(data)
print(output, output.shape)

[[[0.00772376 0.00772376]
  [0.01477655 0.01477655]
  [0.02155165 0.02155165]]] (1, 3, 2)


### LSTM-RNN Test 02

In [7]:
from keras.models import Model
from keras.layers import Input
from keras.layers import LSTM
from numpy import array
import keras
import warnings
warnings.filterwarnings('ignore')

k_init = keras.initializers.Constant(value=0.1)
b_init = keras.initializers.Constant(value=0.0)
r_init = keras.initializers.Constant(value=0.2)
# LSTM units
units = 2

# define model
inputs1 = Input(shape=(3, 2))
# we should setting recurrent_activation = 'sigmoid' because default as 'hard_sigmoid'
lstm = LSTM(units, return_sequences = True, recurrent_activation='sigmoid', use_bias=False, activation='tanh',kernel_initializer=k_init, bias_initializer=b_init, recurrent_initializer=r_init)(inputs1)
model = Model(inputs=inputs1, outputs=lstm)
# define input data
data = array([0.1, 0.2, 0.3, 0.1, 0.2, 0.3]).reshape((1,3,2))
# make and show prediction
output = model.predict(data)
print(output, output.shape)

[[[0.00772376 0.00772376]
  [0.01520084 0.01520084]
  [0.02265241 0.02265241]]] (1, 3, 2)


### LSTM-RNN Test 03

In [8]:
from keras.models import Model
from keras.layers import Input
from keras.layers import LSTM
from numpy import array
import keras
import warnings
warnings.filterwarnings('ignore')

k_init = keras.initializers.Constant(value=0.1)
b_init = keras.initializers.Constant(value=0.0)
r_init = keras.initializers.Constant(value=0.2)
# LSTM units
units = 2

# define model
inputs1 = Input(shape=(3, 2))
# we should setting recurrent_activation = 'sigmoid' because default as 'hard_sigmoid'
lstm = LSTM(units, return_sequences = False, recurrent_activation='sigmoid', use_bias=False, activation='tanh',kernel_initializer=k_init, bias_initializer=b_init, recurrent_initializer=r_init)(inputs1)
model = Model(inputs=inputs1, outputs=lstm)
# define input data
data = array([0.1, 0.2, 0.3, 0.1, 0.2, 0.3]).reshape((1,3,2))
# make and show prediction
output = model.predict(data)
print(output, output.shape)

[[0.02265241 0.02265241]] (1, 2)


###Bonus

In [9]:
for layer in model.layers:
  g=layer.get_config()
  h=layer.get_weights()
  print (g)
  print (h)

{'batch_input_shape': (None, 3, 2), 'dtype': 'float32', 'sparse': False, 'name': 'input_7'}
[]
{'name': 'lstm_5', 'trainable': True, 'return_sequences': False, 'return_state': False, 'go_backwards': False, 'stateful': False, 'unroll': False, 'units': 2, 'activation': 'tanh', 'recurrent_activation': 'sigmoid', 'use_bias': False, 'kernel_initializer': {'class_name': 'Constant', 'config': {'value': 0.1}}, 'recurrent_initializer': {'class_name': 'Constant', 'config': {'value': 0.2}}, 'bias_initializer': {'class_name': 'Constant', 'config': {'value': 0.0}}, 'unit_forget_bias': True, 'kernel_regularizer': None, 'recurrent_regularizer': None, 'bias_regularizer': None, 'activity_regularizer': None, 'kernel_constraint': None, 'recurrent_constraint': None, 'bias_constraint': None, 'dropout': 0.0, 'recurrent_dropout': 0.0, 'implementation': 1}
[array([[0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]], dtype=float32), array([[0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0